name: Unity WebGL Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:
  free-disk-space:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false 

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true 
        dotnet: true 
        haskell: true 
        large-packages: true 
        docker-images: true 
        swap-storage: true 

  test_and_build:
    name: Test and Build Unity Project for WebGL
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - name: Clean Docker environment
      run: |
        docker system prune -f --all
        docker volume prune -f
    - name: Set up Unity Test Runner
      uses: game-ci/unity-test-runner@v4
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      with:
        projectPath: .
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        testMode: playmode
        buildTarget: WebGL
    - name: Build WebGL
      uses: game-ci/unity-builder@v4
      with:
        unityVersion: 2022.3.0f1
        targetPlatform: WebGL
        allowDirtyBuild: true
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: WebGLBuild
        path: build/WebGL
    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: build/WebGL
