name: Build, Test, and Deploy Unity Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-android:
    name: Build and Test Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity
        uses: game-ci/unity-installer@v3

      - name: Run Tests
        uses: game-ci/unity-test-runner@v2
        with:
          targetPlatform: Android

      - name: Build Android
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: Android
          buildName: android

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Android
          path: build/android

  build-ios:
    name: Build and Test iOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity
        uses: game-ci/unity-installer@v3

      - name: Run Tests
        uses: game-ci/unity-test-runner@v2
        with:
          targetPlatform: iOS

      - name: Build iOS
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: iOS
          buildName: ios

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: iOS
          path: build/ios

  build-windows:
    name: Build and Test Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity
        uses: game-ci/unity-installer@v3

      - name: Run Tests
        uses: game-ci/unity-test-runner@v2
        with:
          targetPlatform: StandaloneWindows64

      - name: Build Windows
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64
          buildName: windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: build/windows

  build-webgl:
    name: Build and Test WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity
        uses: game-ci/unity-installer@v3

      - name: Run Tests
        uses: game-ci/unity-test-runner@v2
        with:
          targetPlatform: WebGL

      - name: Build WebGL
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: WebGL
          buildName: webgl

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: WebGL
          path: build/webgl
