name: Build, Test, and Deploy Unity Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64
          - iOS
          - Android
          - WebGL
    steps:
      - name: Checkout repository
        uses: RutgersGRID/custom-checkout-action@v1

      - name: Create directory for outputs
        run: mkdir -p outputs/${{ matrix.targetPlatform }}

      - name: Set up Unity
        uses: RutgersGRID/custom-unity-builder-action@v1
        with:
          outputPath: outputs/${{ matrix.targetPlatform }}

      - name: Run Tests
        uses: RutgersGRID/custom-unity-test-runner-action@v1
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          outputPath: outputs/${{ matrix.targetPlatform }}

      - if: matrix.targetPlatform == 'Android'
        name: Free disk space for Android
        uses: RutgersGRID/custom-free-disk-space-action@v1
        with:
          outputPath: outputs/${{ matrix.targetPlatform }}

      - name: Upload Artifact
        uses: RutgersGRID/custom-upload-artifact-action@v1
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: outputs/${{ matrix.targetPlatform }}
