name: Unity WebGL Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  UNITY_VERSION: 2022.3.16f1
  UNITY_PROJECT_ID: ${{ secrets.UNITY_PROJECT_ID }}

jobs:
  buildWebGL:
    name: Build Unity Project for WebGL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-WebGL-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-WebGL-
            Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: WebGL
          allowDirtyBuild: true
          buildName: Build
          customParameters: -quit -batchmode -nographics -webglheap 512 -webglTemplate DEFAULT

      - uses: actions/upload-artifact@v4
        with:
          name: Build-WebGL
          path: build/WebGL
          retention-days: 14

      - uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: build/WebGL
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
