name: Unity WebGL Build and Test
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  UNITY_VERSION: 2022.3.16f1
  UNITY_PROJECT_ID: ${{ secrets.UNITY_PROJECT_ID }}

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: WebGL
          allowDirtyBuild: true
          buildName: CYOA_Game

      - name: Prepare WebGL Build
        run: |
          sudo mkdir -p build/WebGL
          sudo chmod -R 777 build/WebGL
          sudo touch build/WebGL/.nojekyll
          if [ -d "build/WebGL/CYOA_Game" ]; then
            sudo cp -r build/WebGL/CYOA_Game/* build/WebGL/
            sudo rm -rf build/WebGL/CYOA_Game
          fi
      - uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: build/WebGL
          clean: true