name: Unity WebGL Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  test_and_build:
    name: Test and Build Unity Project for WebGL
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Unity
      uses: actions/cache@v3
      with:
        path: ~/.cache/unity
        key: ${{ runner.os }}-unity-${{ hashFiles('**/Packages/manifest.json') }}
        restore-keys: |
          ${{ runner.os }}-unity-

    - name: Set up Unity Builder
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 2022.3.40f1
        targetPlatform: WebGL

      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

    - name: Run Play Mode Tests
      uses: game-ci/unity-test-runner@v2
      with:
        testMode: playmode
        unityVersion: 2022.3.40f1
        targetPlatform: WebGL

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: WebGLBuild
        path: build/WebGL

    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: build/WebGL
