name: Build, Test, and Deploy Unity Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-android:
    name: Build and Test Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: RutgersGRID/custom-checkout-action@v1  # Custom checkout action
      - name: Set up Unity
        uses: RutgersGRID/custom-unity-installer-action@v1  # Custom Unity installer action
      - name: Run Tests
        uses: RutgersGRID/custom-unity-test-runner-action@v1  # Custom Unity test runner action
        with:
          targetPlatform: Android
      - name: Build Android
        uses: RutgersGRID/custom-unity-builder-action@v1  # Custom Unity builder action
        with:
          targetPlatform: Android
          buildName: android
      - name: Upload Artifact
        uses: RutgersGRID/custom-upload-artifact-action@v1  # Custom artifact upload action
        with:
          name: Android
          path: build/android

  build-ios:
    name: Build and Test iOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: RutgersGRID/custom-checkout-action@v1  # Custom checkout action
      - name: Set up Unity
        uses: RutgersGRID/custom-unity-installer-action@v1  # Custom Unity installer action
      - name: Run Tests
        uses: RutgersGRID/custom-unity-test-runner-action@v1  # Custom Unity test runner action
        with:
          targetPlatform: iOS
      - name: Build iOS
        uses: RutgersGRID/custom-unity-builder-action@v1  # Custom Unity builder action
        with:
          targetPlatform: iOS
          buildName: ios
      - name: Upload Artifact
        uses: RutgersGRID/custom-upload-artifact-action@v1  # Custom artifact upload action
        with:
          name: iOS
          path: build/ios

  build-windows:
    name: Build and Test Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: RutgersGRID/custom-checkout-action@v1  # Custom checkout action
      - name: Set up Unity
        uses: RutgersGRID/custom-unity-installer-action@v1  # Custom Unity installer action
      - name: Run Tests
        uses: RutgersGRID/custom-unity-test-runner-action@v1  # Custom Unity test runner action
        with:
          targetPlatform: StandaloneWindows64
      - name: Build Windows
        uses: RutgersGRID/custom-unity-builder-action@v1  # Custom Unity builder action
        with:
          targetPlatform: StandaloneWindows64
          buildName: windows
      - name: Upload Artifact
        uses: RutgersGRID/custom-upload-artifact-action@v1  # Custom artifact upload action
        with:
          name: Windows
          path: build/windows

  build-webgl:
    name: Build and Test WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: RutgersGRID/custom-checkout-action@v1  # Custom checkout action
      - name: Set up Unity
        uses: RutgersGRID/custom-unity-installer-action@v1  # Custom Unity installer action
      - name: Run Tests
        uses: RutgersGRID/custom-unity-test-runner-action@v1  # Custom Unity test runner action
        with:
          targetPlatform: WebGL
      - name: Build WebGL
        uses: RutgersGRID/custom-unity-builder-action@v1  # Custom Unity builder action
        with:
          targetPlatform: WebGL
          buildName: webgl
      - name: Upload Artifact
        uses: RutgersGRID/custom-upload-artifact-action@v1  # Custom artifact upload action
        with:
          name: WebGL
          path: build/webgl
